### ISSUE TITLE
Error Loading Plugin: pry not found

### ISSUE THREAD

**Issue by brianlenz** [google-checks/checks-fastlane-plugin#4]
We're trying to hook up Fastlane to upload our iOS builds to Checks. We've followed the [install guidelines](https://developers.google.com/checks/guide/integrate/ci-cd/ci-cd-setup?plugin=fastlane) and have the plugin installed. We're getting this error on initializing Fastlane, however:

```
[16:37:59]: Error loading plugin 'fastlane-plugin-checks': cannot load such file -- pry
Did you mean?  pty
[16:37:59]: It seems like you wanted to load some plugins, however they couldn't be loaded
[16:37:59]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
+-----------------------------------------------------+
|                    Used plugins                     |
+------------------------+---------+------------------+
| Plugin                 | Version | Action           |
+------------------------+---------+------------------+
| fastlane-plugin-checks | 0.2.0   | No actions found |
+------------------------+---------+------------------+

[!] No actions were found while loading one or more plugins
    Please use `bundle exec fastlane` with plugins
    More info - https://docs.fastlane.tools/plugins/using-plugins/#run-with-plugins
```

Then, when we try to run the action, it results in:

```
[16:38:30]: Could not find action, lane or variable 'upload_to_checks'. Check out the documentation for more details: https://docs.fastlane.tools/actions
```

Any idea what is causing this or how to work around it? Is there something we need to do to get `pry` working? I've tried using Ruby `3.1.2` and `3.3.0`, but the same issue persists.

I see `pry` is listed as a dev dependency:

https://github.com/google-checks/checks-fastlane-plugin/blob/main/fastlane-plugin-checks.gemspec#L28

Is it supposed to be a full dependency instead?

**Comment by evanotero** [comment]
Hey Brian! Apologies for the errors that you're seeing. It looks like the documentation at https://developers.google.com/checks/guide/integrate/ci-cd/ci-cd-setup?plugin=fastlane is out-of-date.

The correct name for the action is `checks_app_scan`. The [README](https://github.com/google-checks/checks-fastlane-plugin/blob/main/README.md) should be up-to-date with that information. We'll work on getting that documentation updated.

As for the dependency error, let me know if that goes away after using `checks_app_scan`. If you're still seeing that error, @sherzat3 and I can take another look.

**Comment by brianlenz** [comment]
Thanks for the quick reply, @evanotero! I switched it over to `checks_app_scan`, but the same issue persists with `pry` 🤔 The errors are identical (can't load plugin and can't find action `'checks_app_scan'`.

**Comment by evanotero** [comment]
**Update**: Removed the `pry` dependency and now the action is appearing. I'll open a PR, which we should be able to review and merge tomorrow. We'll cut a new release and update here once that's available on RubyGems.

```
+----------------------------------------------------+
|                    Used plugins                    |
+------------------------+---------+-----------------+
| Plugin                 | Version | Action          |
+------------------------+---------+-----------------+
| fastlane-plugin-checks | 0.2.0   | checks_app_scan |
+------------------------+---------+-----------------+
```

**Comment by brianlenz** [comment]
Thanks for the fix, @evanotero! Any idea when a new plugin version might be published?

**Comment by evanotero** [comment]
We had to fix one more bug, but now the release is out! https://rubygems.org/gems/fastlane-plugin-checks/versions/0.2.1

Let us know if you run into any more issues, @brianlenz. Really appreciate your patience.

**Comment by brianlenz** [comment]
Thanks so much, @evanotero! The plugin does seem to function without error now 💪 The issue for us know is that we're getting a `403` error:

> Caller does not have required permission to use project --redacted--. Grant the caller the roles/serviceusage.serviceUsageConsumer role, or a custom role with the serviceusage.services.use permission, by visiting https://console.developers.google.com/iam-admin/iam/project?project=redacted and then retry. Propagation of the new permission may take a few minutes.

We followed the docs to set the Service Account up:

https://developers.google.com/checks/guide/integrate/cli/install-checks-cli#authenticate-cli

Apparently there is another step missing from the docs?

The Service Account is an admin in Checks, but based on this error, it seems that there's more required from a permission standpoint?

Other documentation issues:

1. The "Authenticate CLI" link in the [CI/CD setup docs](https://developers.google.com/checks/guide/integrate/ci-cd/ci-cd-setup?plugin=fastlane) is broken. It links to [broken link](https://developers.google.com/checks/guide/cli/install-checks-cli#authenticate-service).
    * The same issue exists with the "Authenticate CLI" link in the GitHub [README](https://github.com/google-checks/checks-fastlane-plugin?tab=readme-ov-file). It links to [broken link](https://github.com/google-checks/checks-fastlane-plugin/blob/main/checks/guide/cli/install-checks-cli#authenticate-service).
2. The [docs](https://developers.google.com/checks/guide/integrate/ci-cd/ci-cd-setup?plugin=fastlane) say you should Base64-encode the Service Account JSON file. I had done that originally, which fails. I then followed the instructions in the GitHub [README](https://github.com/google-checks/checks-fastlane-plugin?tab=readme-ov-file) so that it references the file path, and that worked 👍 (with the exception of the permissions error above)

**Comment by brianlenz** [comment]
@evanotero I got the Service Account working! The [Authenticate the CLI](https://developers.google.com/checks/guide/integrate/cli/install-checks-cli#authenticate-cli) docs need to be updated to mention granting the new Service Account the Service Usage Consumer role in the project (https://console.cloud.google.com/iam-admin/iam?project=XXX). Once that is done, _then_ the integration works. 🚀

**Comment by evanotero** [comment]
Thanks Brian for catching those issues! We'll get that documentation updated ASAP.
